.TH PWN 1 pwn\-VERSION
.SH NAME
pwn \- simple multiplayer chess game
.SH SYNOPSIS
\fI pwn\fR -l\ address -p port [-s\ color] [-t\ time]
\fI pwn\fR -c\ address
.SH DESCRIPTION
pwn is a simple multiplayer chess game for the X Window System. It supports playing with time
control and playing over a network.
.SH OPTIONS
.TP
.B \-l address
Set
.I address
as the IP address on which the progamm shall listen for a connection by an opponent.
.TP
.B \-c address
Set
.I address
as the IP address of the opponent to whom the connection shall be established. This option implies
that you are playing with the opposite color of the one specified by your oppenent.
.TP
.B \-p port
Set
.I port
as the port number on which the progamm shall listen for a connection by an opponent.
.TP
.B \-s color
Set
.I color
as the color you want to play with. A valid color is either
.I black
or
.I white\fR.
This option can only be specified when you are listening for an incoming connection by your opponent.
After a successfull connection your opponent will be playing with the opposite color of the one you
specified. If this option is omitted the color gets chosen randomly.
.TP
.B \-t time
Set
.I time
as the total time each player has for the game. It has to be specified in the format
.I h:m[+s]
where
.I h
are the hours and
.I m
the minutes each player gets. Additionally
.I s
specifies an (optional) increment that will be added to the total timespan of each player every
time they make a move. If a player has used up all of his time before the game was finished the game
will be decided either by a draw or by a loss for the respective player. There will be no time
limit if this option is omitted.
.SH EXAMPLES
As an example: If Alice wants to host a game as \fIblack\fR with \fI1 hour and 30 minutes\fR clock
time and \fI10 seconds\fR increment on the adress \fI192.168.0.2\fR with port number \fI5000\fR she would run
.sp
.RS 4
.nf
pwn -l 192.168.0.2 -p 5000 -s black -t 1:30+10
.fi
.P
.RE
.P
Then Bob would have to run
.sp
.RS 4
.nf
pwn -c 192.168.0.2
.fi
.P
.RE
.P
to connect to Alice and play a game with the white pieces against her.
